targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  viewBuilder:
    target: ":generators"
    import: "package:intl_skltn/intl_skltn.dart"
    builder_factories: ["viewBuilder"] #Builder name(BuilderOptions)
    build_extensions: { ".dart": [".view.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".view.part"]
    applies_builders: ["source_gen"]
